# Tugas 1 / 06211640000022

In [8]:
# Data integration
import pandas as pd
import numpy as np

In [9]:
# load data
populasi = pd.read_csv ('populasi.csv')
inflasi=pd.read_csv('inflasi.csv')
populasi

      ID            country  year   populasi
0    13I          Indonesia  2013  252032263
1    13P        Philippines  2013   98481032
2    13M           Malaysia  2013   29706724
3    13S          Singapore  2013    5399162
4    13T           Thailand  2013   68143065
5    13B  Brunei Darussalam  2013     405716
6    13V            Vietnam  2013   91497725
7    13L            Lao PDR  2013    6494557
8   13My            Myanmar  2013   51448196
9    13C           Cambodia  2013   15022692
10   14I          Indonesia  2014  255131116
11   14P        Philippines  2014  100102249
12   14M           Malaysia  2014   30228017
13   14S          Singapore  2014    5469724
14   14T           Thailand  2014   68416772
15   14B  Brunei Darussalam  2014     411704
16   14V            Vietnam  2014   92544915
17   14L            Lao PDR  2014    6576397
18  14My            Myanmar  2014   51924182
19   14C           Cambodia  2014   15270790
20   15I          Indonesia  2015  258162113
21   15P        Philippines  2015  101716359
22   15M           Malaysia  2015   30723155
23   15S          Singapore  2015    5535002
24   15T           Thailand  2015   68657600
25   15B  Brunei Darussalam  2015     417542
26   15V            Vietnam  2015   93571567
27   15L            Lao PDR  2015    6663967
28  15My            Myanmar  2015   52403669
29   15C           Cambodia  2015   15517635
30   16I          Indonesia  2016  261115456
31   16P        Philippines  2016  103320222
32   16M           Malaysia  2016   31187265
33   16S          Singapore  2016    5607283
34   16T           Thailand  2016   68863514
35   16B  Brunei Darussalam  2016     423196
36   16V            Vietnam  2016   94569072
37   16L            Lao PDR  2016    6758353
38  16My            Myanmar  2016   52885223
39   16C           Cambodia  2016   15762370
40   17I          Indonesia  2017  263991379
41   17P        Philippines  2017  104918090
42   17M           Malaysia  2017   31624264
43   17S          Singapore  2017    5612253
44   17T           Thailand  2017   69037513
45   17B  Brunei Darussalam  2017     428697
46   17V            Vietnam  2017   95540800
47   17L            Lao PDR  2017    6858160
48  17My            Myanmar  2017   53370609
49   17C           Cambodia  2017   16005373

In [10]:
inflasi

      ID   inflasi         ihk      gdp
0    13I  6.412513  116.909852   912524
1    13P  2.582688  110.674621   271836
2    13M  2.105012  107.098817   323277
3    13S  2.358601  112.659983   304454
4    13T  2.184886  109.275006   420333
5    13B  0.389205  100.640009    18094
6    13V  6.592256  138.002976   171222
7    13L  6.371427  119.291498    11942
8   13My  5.483386  112.405984    60270
9    13C  2.942600  111.766823    15228
10   14I  6.394925  124.386150   890815
11   14P  3.597823  114.656499   284585
12   14M  3.142991  110.464923   338062
13   14S  1.024983  113.814728   311539
14   14T  1.895142  111.345923   407339
15   14B -0.207109  100.431575    17098
16   14V  4.710018  144.502941   186205
17   14L  4.129243  124.217334    13268
18  14My  5.046411  118.078452    65446
19   14C  3.855239  116.075701    16703
20   15I  6.363121  132.300991   860854
21   15P  0.674193  115.429504   292774
22   15M  2.104390  112.789535   296434
23   15S -0.522752  113.219759   304098
24   15T -0.900425  110.343336   401399
25   15B -0.415122  100.014662    12930
26   15V  0.878604  145.772550   193241
27   15L  1.277354  125.804029    14390
28  15My  9.485473  129.278751    59687
29   15C  1.221270  117.493299    18050
30   16I  3.525805  136.965667   932256
31   16P  1.253699  116.876642   304889
32   16M  2.090567  115.147475   296536
33   16S -0.532286  112.617106   309764
34   16T  0.188150  110.550947   411755
35   16B -0.739069   99.275485    11401
36   16V  3.243567  150.500780   205276
37   16L  1.596796  127.812862    15806
38  16My  6.964739  138.282679    63225
39   16C  3.045415  121.071457    20017
40   17I  3.808798  142.182412  1015539
41   17P  2.853188  120.211352   313595
42   17M  3.871201  119.605066   314500
43   17S  0.576325  113.266146   323907
44   17T  0.665632  111.286809   455221
45   17B -0.171312   99.105414    12128
46   17V  3.520257  155.798795   223864
47   17L  0.825160  128.867523    16853
48  17My  4.572727  144.605969    69322
49   17C  2.890925  124.571541    22158

In [11]:
# merge data based on ID
data = pd.merge(populasi, inflasi, on='ID')
data

      ID            country  year   populasi   inflasi         ihk      gdp
0    13I          Indonesia  2013  252032263  6.412513  116.909852   912524
1    13P        Philippines  2013   98481032  2.582688  110.674621   271836
2    13M           Malaysia  2013   29706724  2.105012  107.098817   323277
3    13S          Singapore  2013    5399162  2.358601  112.659983   304454
4    13T           Thailand  2013   68143065  2.184886  109.275006   420333
5    13B  Brunei Darussalam  2013     405716  0.389205  100.640009    18094
6    13V            Vietnam  2013   91497725  6.592256  138.002976   171222
7    13L            Lao PDR  2013    6494557  6.371427  119.291498    11942
8   13My            Myanmar  2013   51448196  5.483386  112.405984    60270
9    13C           Cambodia  2013   15022692  2.942600  111.766823    15228
10   14I          Indonesia  2014  255131116  6.394925  124.386150   890815
11   14P        Philippines  2014  100102249  3.597823  114.656499   284585
12   14M           Malaysia  2014   30228017  3.142991  110.464923   338062
13   14S          Singapore  2014    5469724  1.024983  113.814728   311539
14   14T           Thailand  2014   68416772  1.895142  111.345923   407339
15   14B  Brunei Darussalam  2014     411704 -0.207109  100.431575    17098
16   14V            Vietnam  2014   92544915  4.710018  144.502941   186205
17   14L            Lao PDR  2014    6576397  4.129243  124.217334    13268
18  14My            Myanmar  2014   51924182  5.046411  118.078452    65446
19   14C           Cambodia  2014   15270790  3.855239  116.075701    16703
20   15I          Indonesia  2015  258162113  6.363121  132.300991   860854
21   15P        Philippines  2015  101716359  0.674193  115.429504   292774
22   15M           Malaysia  2015   30723155  2.104390  112.789535   296434
23   15S          Singapore  2015    5535002 -0.522752  113.219759   304098
24   15T           Thailand  2015   68657600 -0.900425  110.343336   401399
25   15B  Brunei Darussalam  2015     417542 -0.415122  100.014662    12930
26   15V            Vietnam  2015   93571567  0.878604  145.772550   193241
27   15L            Lao PDR  2015    6663967  1.277354  125.804029    14390
28  15My            Myanmar  2015   52403669  9.485473  129.278751    59687
29   15C           Cambodia  2015   15517635  1.221270  117.493299    18050
30   16I          Indonesia  2016  261115456  3.525805  136.965667   932256
31   16P        Philippines  2016  103320222  1.253699  116.876642   304889
32   16M           Malaysia  2016   31187265  2.090567  115.147475   296536
33   16S          Singapore  2016    5607283 -0.532286  112.617106   309764
34   16T           Thailand  2016   68863514  0.188150  110.550947   411755
35   16B  Brunei Darussalam  2016     423196 -0.739069   99.275485    11401
36   16V            Vietnam  2016   94569072  3.243567  150.500780   205276
37   16L            Lao PDR  2016    6758353  1.596796  127.812862    15806
38  16My            Myanmar  2016   52885223  6.964739  138.282679    63225
39   16C           Cambodia  2016   15762370  3.045415  121.071457    20017
40   17I          Indonesia  2017  263991379  3.808798  142.182412  1015539
41   17P        Philippines  2017  104918090  2.853188  120.211352   313595
42   17M           Malaysia  2017   31624264  3.871201  119.605066   314500
43   17S          Singapore  2017    5612253  0.576325  113.266146   323907
44   17T           Thailand  2017   69037513  0.665632  111.286809   455221
45   17B  Brunei Darussalam  2017     428697 -0.171312   99.105414    12128
46   17V            Vietnam  2017   95540800  3.520257  155.798795   223864
47   17L            Lao PDR  2017    6858160  0.825160  128.867523    16853
48  17My            Myanmar  2017   53370609  4.572727  144.605969    69322
49   17C           Cambodia  2017   16005373  2.890925  124.571541    22158

In [14]:
# insert new colomn
data['%inflasi'] =(data['inflasi']*100)
data

,ID,country,year,populasi,inflasi,ihk,gdp,populasi/inflasi,%inflasi
0,13I,Indonesia,2013,252032263,6.412513,116.909852,912524,3.930320e+07,641.251330
1,13P,Philippines,2013,98481032,2.582688,110.674621,271836,3.813122e+07,258.268766
2,13M,Malaysia,2013,29706724,2.105012,107.098817,323277,1.411238e+07,210.501231
3,13S,Singapore,2013,5399162,2.358601,112.659983,304454,2.289137e+06,235.860115
4,13T,Thailand,2013,68143065,2.184886,109.275006,420333,3.118838e+07,218.488618
5,13B,Brunei Darussalam,2013,405716,0.389205,100.640009,18094,1.042422e+06,38.920505
6,13V,Vietnam,2013,91497725,6.592256,138.002976,171222,1.387958e+07,659.225590
7,13L,Lao PDR,2013,6494557,6.371427,119.291498,11942,1.019325e+06,637.142718
8,13My,Myanmar,2013,51448196,5.483386,112.405984,60270,9.382559e+06,548.338619
9,13C,Cambodia,2013,15022692,2.942600,111.766823,15228,5.105244e+06,294.260016
10,14I,Indonesia,2014,255131116,6.394925,124.386150,890815,3.989587e+07,639.492541
11,14P,Philippines,2014,100102249,3.597823,114.656499,284585,2.782300e+07,359.782344
12,14M,Malaysia,2014,30228017,3.142991,110.464923,338062,9.617597e+06,314.299051
13,14S,Singapore,2014,5469724,1.024983,113.814728,311539,5.336407e+06,102.498253
14,14T,Thailand,2014,68416772,1.895142,111.345923,407339,3.610114e+07,189.514182
15,14B,Brunei Darussalam,2014,411704,-0.207109,100.431575,17098,-1.987864e+06,-20.710873
16,14V,Vietnam,2014,92544915,4.710018,144.502941,186205,1.964853e+07,471.001843
17,14L,Lao PDR,2014,6576397,4.129243,124.217334,13268,1.592640e+06,412.924307
18,14My,Myanmar,2014,51924182,5.046411,118.078452,65446,1.028933e+07,504.641089
19,14C,Cambodia,2014,15270790,3.855239,116.075701,16703,3.961049e+06,385.523855
20,15I,Indonesia,2015,258162113,6.363121,132.300991,860854,4.057162e+07,636.312113
21,15P,Philippines,2015,101716359,0.674193,115.429504,292774,1.508714e+08,67.419254
22,15M,Malaysia,2015,30723155,2.104390,112.789535,296434,1.459956e+07,210.438980
23,15S,Singapore,2015,5535002,-0.522752,113.219759,304098,-1.058819e+07,-52.275249
24,15T,Thailand,2015,68657600,-0.900425,110.343336,401399,-7.625022e+07,-90.042496
25,15B,Brunei Darussalam,2015,417542,-0.415122,100.014662,12930,-1.005830e+06,-41.512193
26,15V,Vietnam,2015,93571567,0.878604,145.772550,193241,1.065003e+08,87.860371
27,15L,Lao PDR,2015,6663967,1.277354,125.804029,14390,5.217008e+06,127.735427
28,15My,Myanmar,2015,52403669,9.485473,129.278751,59687,5.524624e+06,948.547255
29,15C,Cambodia,2015,15517635,1.221270,117.493299,18050,1.270615e+07,122.127006
30,16I,Indonesia,2016,261115456,3.525805,136.965667,932256,7.405839e+07,352.580516
31,16P,Philippines,2016,103320222,1.253699,116.876642,304889,8.241232e+07,125.369880
32,16M,Malaysia,2016,31187265,2.090567,115.147475,296536,1.491809e+07,209.056659
33,16S,Singapore,2016,5607283,-0.532286,112.617106,309764,-1.053434e+07,-53.228613
34,16T,Thailand,2016,68863514,0.188150,110.550947,411755,3.660038e+08,18.814970
35,16B,Brunei Darussalam,2016,423196,-0.739069,99.275485,11401,-5.726071e+05,-73.906872
36,16V,Vietnam,2016,94569072,3.243567,150.500780,205276,2.915588e+07,324.356743
37,16L,Lao PDR,2016,6758353,1.596796,127.812862,15806,4.232447e+06,159.679563
38,16My,Myanmar,2016,52885223,6.964739,138.282679,63225,7.593281e+06,696.473918
39,16C,Cambodia,2016,15762370,3.045415,121.071457,20017,5.175771e+06,304.541464
40,17I,Indonesia,2017,263991379,3.808798,142.182412,1015539,6.931094e+07,380.879807
41,17P,Philippines,2017,104918090,2.853188,120.211352,313595,3.677224e+07,285.318773
42,17M,Malaysia,2017,31624264,3.871201,119.605066,314500,8.169109e+06,387.120116
43,17S,Singapore,2017,5612253,0.576325,113.266146,323907,9.738005e+06,57.632470
44,17T,Thailand,2017,69037513,0.665632,111.286809,455221,1.037173e+08,66.563189
45,17B,Brunei Darussalam,2017,428697,-0.171312,99.105414,12128,-2.502441e+06,-17.131152
46,17V,Vietnam,2017,95540800,3.520257,155.798795,223864,2.714029e+07,352.025689
47,17L,Lao PDR,2017,6858160,0.825160,128.867523,16853,8.311312e+06,82.515969
48,17My,Myanmar,2017,53370609,4.572727,144.605969,69322,1.167150e+07,457.272733
49,17C,Cambodia,2017,16005373,2.890925,124.571541,22158,5.536420e+06,289.092469

In [15]:
# delete colomn
data1 = data.drop(['populasi/inflasi'], axis=1)
data1

,ID,country,year,populasi,inflasi,ihk,gdp,%inflasi
0,13I,Indonesia,2013,252032263,6.412513,116.909852,912524,641.251330
1,13P,Philippines,2013,98481032,2.582688,110.674621,271836,258.268766
2,13M,Malaysia,2013,29706724,2.105012,107.098817,323277,210.501231
3,13S,Singapore,2013,5399162,2.358601,112.659983,304454,235.860115
4,13T,Thailand,2013,68143065,2.184886,109.275006,420333,218.488618
5,13B,Brunei Darussalam,2013,405716,0.389205,100.640009,18094,38.920505
6,13V,Vietnam,2013,91497725,6.592256,138.002976,171222,659.225590
7,13L,Lao PDR,2013,6494557,6.371427,119.291498,11942,637.142718
8,13My,Myanmar,2013,51448196,5.483386,112.405984,60270,548.338619
9,13C,Cambodia,2013,15022692,2.942600,111.766823,15228,294.260016
10,14I,Indonesia,2014,255131116,6.394925,124.386150,890815,639.492541
11,14P,Philippines,2014,100102249,3.597823,114.656499,284585,359.782344
12,14M,Malaysia,2014,30228017,3.142991,110.464923,338062,314.299051
13,14S,Singapore,2014,5469724,1.024983,113.814728,311539,102.498253
14,14T,Thailand,2014,68416772,1.895142,111.345923,407339,189.514182
15,14B,Brunei Darussalam,2014,411704,-0.207109,100.431575,17098,-20.710873
16,14V,Vietnam,2014,92544915,4.710018,144.502941,186205,471.001843
17,14L,Lao PDR,2014,6576397,4.129243,124.217334,13268,412.924307
18,14My,Myanmar,2014,51924182,5.046411,118.078452,65446,504.641089
19,14C,Cambodia,2014,15270790,3.855239,116.075701,16703,385.523855
20,15I,Indonesia,2015,258162113,6.363121,132.300991,860854,636.312113
21,15P,Philippines,2015,101716359,0.674193,115.429504,292774,67.419254
22,15M,Malaysia,2015,30723155,2.104390,112.789535,296434,210.438980
23,15S,Singapore,2015,5535002,-0.522752,113.219759,304098,-52.275249
24,15T,Thailand,2015,68657600,-0.900425,110.343336,401399,-90.042496
25,15B,Brunei Darussalam,2015,417542,-0.415122,100.014662,12930,-41.512193
26,15V,Vietnam,2015,93571567,0.878604,145.772550,193241,87.860371
27,15L,Lao PDR,2015,6663967,1.277354,125.804029,14390,127.735427
28,15My,Myanmar,2015,52403669,9.485473,129.278751,59687,948.547255
29,15C,Cambodia,2015,15517635,1.221270,117.493299,18050,122.127006
30,16I,Indonesia,2016,261115456,3.525805,136.965667,932256,352.580516
31,16P,Philippines,2016,103320222,1.253699,116.876642,304889,125.369880
32,16M,Malaysia,2016,31187265,2.090567,115.147475,296536,209.056659
33,16S,Singapore,2016,5607283,-0.532286,112.617106,309764,-53.228613
34,16T,Thailand,2016,68863514,0.188150,110.550947,411755,18.814970
35,16B,Brunei Darussalam,2016,423196,-0.739069,99.275485,11401,-73.906872
36,16V,Vietnam,2016,94569072,3.243567,150.500780,205276,324.356743
37,16L,Lao PDR,2016,6758353,1.596796,127.812862,15806,159.679563
38,16My,Myanmar,2016,52885223,6.964739,138.282679,63225,696.473918
39,16C,Cambodia,2016,15762370,3.045415,121.071457,20017,304.541464
40,17I,Indonesia,2017,263991379,3.808798,142.182412,1015539,380.879807
41,17P,Philippines,2017,104918090,2.853188,120.211352,313595,285.318773
42,17M,Malaysia,2017,31624264,3.871201,119.605066,314500,387.120116
43,17S,Singapore,2017,5612253,0.576325,113.266146,323907,57.632470
44,17T,Thailand,2017,69037513,0.665632,111.286809,455221,66.563189
45,17B,Brunei Darussalam,2017,428697,-0.171312,99.105414,12128,-17.131152
46,17V,Vietnam,2017,95540800,3.520257,155.798795,223864,352.025689
47,17L,Lao PDR,2017,6858160,0.825160,128.867523,16853,82.515969
48,17My,Myanmar,2017,53370609,4.572727,144.605969,69322,457.272733
49,17C,Cambodia,2017,16005373,2.890925,124.571541,22158,289.092469